> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# NUMPY


### Some interesting functions

What is numpy? NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

This notebook will exclusively explore 5 different functions that deprived from NumPy.

- numpy.split(ary, indices_or_sections, axis=0)
- numpy.shape(a)
- numpy.resize(a, new_shape)
- numpy.char.center(a, width, fillchar=' ')
- numpy.promote_types(type1, type2) 

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [41]:
!pip install jovian --upgrade -q

In [42]:
import jovian

In [43]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "imhelendang/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/imhelendang/numpy-array-operations


'https://jovian.com/imhelendang/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [44]:
import numpy as np

In [45]:
# List of functions explained 
x = np.arange(9.0) 
function1 = np.split(x, 3) # np.split() will return a list of sub-arrays as views into ary.

function2 = np.shape(np.eye(3)) # returns the shape of the array or the elements of the shape tuple give the lengths of the corresponding array dimensions.

a=np.array([[0,1],[2,3]])
function3 = np.resize(a,(2,3)) # np.resize() will return the new array is formed from the data in the old array, repeated if necessary to fill out the required number of elements. The data are repeated iterating over the array in C-order.

c = np.array(['a1b2','1b2a','b2a1','2a1b']); c
function4 = np.char.center(c, width=9) # np.char.center() will return a copy of a with its elements centered in a string of length width.

function5 = np.promote_types('f4', 'f8') # np.promote_type() will return the data type with the smallest size and smallest scalar kind to which both type1 and type2 may be safely cast. The returned data type is always considered “canonical”, this mainly means that the promoted dtype will always be in native byte order.

## Function 1 - np.split( )

- Split an array into multiple sub-arrays as views into ary.


- Syntax: numpy.split(ary, indices_or_sections, axis=0)
    
    
    + 'ary' is the array to be divided into sub-arrays.

    + 'indices_or_sections' is is an integer, N, the array will be divided into N equal arrays along axis. 
    
        * But, if such a split is not possible, an error is raised (see NOTE below).
        
        * Meanwhile if indices_or_sections is a 1-D array of sorted integers, the entries indicate where along axis the array is split. For example, [2, 3] would, for axis=0, result in ary[:2] or ary[2:3] or ary[3:]. 
        
        * And if an index exceeds the dimension of the array along axis, an empty sub-array is returned correspondingly.

    + 'axis' is optional. The axis along which to split, default is 0.


- RETURN: np.split() will return a list of sub-arrays as views into ary.

In [46]:
# Example 1 
x = np.arange(9.0)

np.split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

The function splits the original array into 3 different arrays.

In [47]:
# Example 2 
x = np.arange(8.0)

np.split(x, [3, 5, 6, 10])

[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7.]),
 array([], dtype=float64)]

Here, the indices_or_sections is a 1-D array of sorted integers, the entries indicate where along axis the array is split as mentioned.

- What did the split function do? 
> It split the array into 5 parts, the first 3 elements, the next 2 elements, the next 1 element, the next 2 elements, and the last 0 elements.

- Why did it return an array of 0 elements at the end?
> Because the last index is 10, which is out of range of the array.

*NOTE ValueError*
- If indices_or_sections is given as an integer, but a split does not result in equal division.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

## Function 2 - np.shape( )

- Syntax: numpy.shape(a)

    + 'a' is a input array.
    

- RETURN: np.shape() returns the shape of the array or the elements of the shape tuple give the lengths of the corresponding array dimensions.

In [ ]:
# Example 1 
np.shape(np.eye(3))

Here, I use np,eye(3) to create a 3x3 identity matrix
Thus, shape() is used to returns the dimensions of the matrix.

In [ ]:
# Example 2 
a = np.array([(1, 2), (3, 4), (5, 6)],dtype=[('x', 'i4'), ('y', 'i4')])

print(a)

np.shape(a)

*A little side note*: dtype is used to creat a structured array. A structured array is an array where each element is a tuple. That makes a an array of tuples. Each tuple has two elements. The first element is an integer and the second element is a string, the data type.

In [ ]:
jovian.commit()

## Function 3 - np.resize( )

- numpy.resize(a, new_shape) - where:


    + 'a' is the array to be resized.

    + 'new_shape' is int or tuple of int which basically is shape of resized array.
    
    + *NOTE*: If the new array is larger than the original array, then the new array is filled with repeated copies of a. Note that this behavior is different from a.resize(new_shape) which fills with zeros instead of repeated copies of a.


- RETURN: np.resize() will return the new array is formed from the data in the old array, repeated if necessary to fill out the required number of elements. The data are repeated iterating over the array in C-order.

In [ ]:
# Example 1
a=np.array([[0,1],[2,3]])

np.resize(a,(2,3))

 - np.resize() will return a new array with the specified shape. If the new array is larger than the original array, then the new array is filled with repeated copies of a. 

- *Note* that this behavior is different from a.resize(new_shape) which fills with zeros instead of repeated copies of a.


In [ ]:
# Example 2
np.resize(a,(1,4))

In [ ]:
# Example 3
np.resize(a,(2,10))

*NOTE*
- When the total size of the array does not change reshape should be used. In most other cases either indexing (to reduce the size) or padding (to increase the size) may be a more appropriate solution.

In [ ]:
jovian.commit()

## Function 4 - np.char.center( )

- Syntax: char.center(a, width, fillchar=' ') - where:


    + 'a' is array_like of str or unicode

    + 'widthint' is the length of the resulting strings
    
    + 'fillcharstr' or unicode, is optional, is the padding character to use (default is space).


- RETURN: np.char.center() will return a copy of a with its elements centered in a string of length width.

In [ ]:
# Example 1
c = np.array(['a1b2','1b2a','b2a1','2a1b'])

np.char.center(c, width=9)

Explanation about example

In [ ]:
# Example 2
np.char.center(c, width=9, fillchar='*')

Explanation about example

In [ ]:
# Example 3
c = np.array([0,1,2,3])
np.char.center(c, width=1)

In [ ]:
# To fix
c = np.array([0,'1',2,3]) # now the array is array of strings

np.char.center(c, width=1)

This function is intended to work with arrays of strings. The fill character is not applied to numeric types.

In [ ]:
jovian.commit()

## Function 5 - np.promote_type( )

- Syntax: numpy.promote_types(type1, type2):


    + 'type1dtype' or dtype specifier is the first data type.

    + 'type2dtype' or dtype specifier is the second data type.


- RETURN: np.promote_type() will return the data type with the smallest size and smallest scalar kind to which both type1 and type2 may be safely cast. The returned data type is always considered “canonical”, this mainly means that the promoted dtype will always be in native byte order.

In [ ]:
# Example 1 

np.promote_types('f4', 'f8') # f4 is float32 and f8 is float64  

f8 is float64 while f4 is float32. 64 bits contain 32 bits; thus, the result should be float64

In [ ]:
# Example 2
np.promote_types('i8', 'f4')

Since i8 is int64, f4 is float32. and float contains integer and 64 bits contains 32 bits, so the result is int64

In [ ]:
# Example 3 
p = np.promote_types

p('S', p('i1', 'u1'))

Let break down the code above:
- 'S' is the string type
- 'i1' is the 8-bit signed integer type
- 'u1' is the 8-bit unsigned integer type
- p('i1', 'u1') returns 'i2' which is the 16-bit signed integer type
- Therefore, p('S', 'i2') will return 'S' which is the string type as string is the highest type in the hierarchy

*Side note*: S6 is the string type with 6 characters or 6 bits

Be cautious about the data are being used. Please see 'numpy.result_type' for additional information about promotion.

In [ ]:
jovian.commit()

## Conclusion

- So, I have introduced some interesting functions which are deprived from NumPy library. In short, numpy is a python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices.

- Numpy functions are functions that are used to perform mathematical operations on arrays. Numpy functions are used to perform mathematical operations on arrays. And they are mostly preffered when working with big data as numpy functions are faster than python functions.


## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* What is NumPy? https://numpy.org/doc/stable/user/whatisnumpy.html
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html


In [ ]:
jovian.commit()